### PR TITLE
 Module 04 - Conversational AI

### PR DESCRIPTION
**Pull request by DOMINION-JOHN1**
This PR introduces the completed Module 04: Conversational AI, covering key concepts in chat agent design and system context management. It includes four notebooks:

Notebook 01: Building Chat Agents
Notebook 02: System Context Management 
Notebook 03: Multi-Turn Conversations
Notebook 04: Conversation Memory

### CODE REVIEW

**Comment by cobycloud** [comment]
on notebook 3 - multiturn conversations, please also demonstrate how to use `conversation.add_messages()` to add an array of messages in a single call.

**Comment by cobycloud** [comment]
on notebook 4, when demonstrating the SessionCacheConversation, please demonstrate the difference between max size and session cache max size.

Max Size relates to how much the model is actually aware of, while session cache size relates to how much the user is able to see printed out.

Imagine that you have created a chat app and you want your users to see the last 100 messages of the conversation, but you only want the model to be aware of the last 3 messages. In this scenario, we would set max size to 3 and set our session cache max size to 100. This way our user can see 100 messages of history, but the ai will only be aware of the last few messages. 

This is helpful if we want to keep token cost low but still allow the user to be able to recall previous parts of the conversation.

**Comment by DOMINION-JOHN1** [comment]
Alright thanks. On it, Will implement changes now.

**Comment by DOMINION-JOHN1** [comment]
Alright thanks. On it, Will implement changes now.

**Comment by DOMINION-JOHN1** [comment]
for the notebook 4 I noticed there isn't any parameter to set the session cache size and it only Takes in max size. So demonstrating the differences i  code seem difficult. 
OR Do you mean i should compare max size of session_cache conversation and max size of the normal conversation.

**Comment by DOMINION-JOHN1** [comment]
@cobycloud I have updated the notebooks with the correction. Thanks

**Comment by cobycloud** [comment]
image
^please correct this. conversation 2 is showing a long model memory and with a longer user chat history

max_size = model memory
session_max_size = user chat history

**Comment by DOMINION-JOHN1** [comment]
oh sorry that was an oversight. Correction effected. Thanks

**Review by cobycloud — APPROVED** [review]

**Pull request merged**
